# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 51cc5909b106fa65899fff40a6f77eb815af2f98b65d95081918715c537bb4a09d2b5214d257958fc07d296aaa3807bc2d32c8a0b0460bb1acd5ec810bd7b1f7

test:
  secret_key_base: c6b6ce286a14b091ebdbeb26af669fba8454034747c05b87a2df39c0a3e2e1fa8d713e104d5995220b8ed88f31ba4b3eb249b5b6d828fdd75d324fbbd87a1f0c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
